version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "${DOCKER_NGINX_PORT}:${SITE_PORT}"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: mysql
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/var/www
      - composer:/root/.composer/cache
    depends_on:
      - mysql
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: mysql
  mysql:
    image: mysql:8
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DOCKER_MYSQL_PORT}:${DB_PORT}"
  chrome:
    image: selenium/standalone-chrome
    ports:
      - '4444'
      - '5900'

volumes:
  mysql:
  composer: